### ISSUE TITLE
Cannot send two requests withot restarting kernel

### ISSUE THREAD

**Issue by fbottazzoli** [therealexpertai/nlapi-python#15] opened 2022-02-24 19:24 UTC
Hello, I'm trying to replicate the request to API described in play_with_expertai_nlapi_v2 notebook.ipynb. 
I can successfully run the first request to client.specific_resource_analysis but, if I try to run it again, I receive a Error: Incorrect padding. 
If I restart the Python Kernel, I can correctly continue invoking the API (just once).
Can you please help me?
If this can help, I'm using the free account for testing purposes. 
Thank you in advance,
Francesca

**Comment by avarone-github** [comment] 2022-02-25 11:47
Hello Francesca, I'm looking at the issue in the Jupyter notebbok. Do you have the same in a Python script "outside" Jupyter?

**Comment by fbottazzoli** [comment] 2022-02-25 12:14
Hi @avarone-github , honestly I didn't try and I couldn't try immediately :( 
I will let you know if I can test outside Jupyter

**Comment by fbottazzoli** [comment] 2022-02-25 16:49
Hi @avarone-github , not sure if I did exactly what you asked . I did:
- Download the file as .py
- Run the py file from Anaconda prompt.
I got exactly the same result.
Hope I answered you. Thank you,
Francesca

**Comment by avarone-github** [comment] 2022-02-25 17:36
Francesca, I'm sorry, I cannot reproduce the problem.
I'm able to run the `play_with_expertai_nlapi_v2.ipynb` notebook multiple times without restarting the kernel and no error. Also I downloaded the notebook as `.py` and ran it using `ipython` multiple times. I commented out the lines beginning with `get_ipython()` and I was able to run the script with plain Python from the command line prompt. In this case charts are displayed in a pop-up window and you have to close it to go on with the script.
If you install the Python package with:

`pip install expertai-nlapi`

or:

`conda install -c conda-forge expertai-nlapi`

and then you download and run multiple times one of the script under the `samples/natural language api/` folder you can find in this repository, does it work?
Another question: does you developer account password contain spaces?

**Comment by fbottazzoli** [comment] 2022-02-27 09:51
Hi @avarone-github ,
I tried executing sentiment-analysis.py script from the `samples/natural language api/` folder and I can correctly execute it several times. However, I then tried to modify the script as follows and I get again the same error.

```
from expertai.nlapi.cloud.client import ExpertAiClient
client = ExpertAiClient()

text = "Michael Jordan was one of the best basketball players of all time. Scoring was Jordan's stand-out skill, but he still holds a defensive NBA record, with eight steals in a half." 
language= 'en'

output = client.specific_resource_analysis(
    body={"document": {"text": text}}, 
    params={'language': language, 'resource': 'sentiment'
})

# Output overall sentiment

print("Output overall sentiment:")

print(output.sentiment.overall)

## New piece of code

client2 = ExpertAiClient()

text = "Michael Jordan was one of the best basketball players of all time." 
language= 'en'

output = client2.specific_resource_analysis(
    body={"document": {"text": text}}, 
    params={'language': language, 'resource': 'sentiment'
})

# Output overall sentiment

print("Output overall sentiment:")

print(output.sentiment.overall)
```

About the password, after your comment, I changed it with a password containing only letters, numbers and a ! symbol. My username instead is just an email address.

Thank you for your precious help and support!
Francesca

**Comment by avarone-github** [comment] 2022-03-01 08:19
Thank you Francesca. Again, I wasn't able to reproduce the problem, also with your code, however I will continue investigation.

**Comment by avarone-github** [comment] 2022-03-01 09:18
@fbottazzoli, which version of Python are you using? I see the Base64 encoding and decoding functions changed quite a lot in the recent versions (see [here](https://docs.python.org/3/library/base64.html)).
You should use version 3.7 or later.

**Comment by fbottazzoli** [comment] 2022-03-01 18:59
Hi @avarone-github , I checked:

```
conda -V
conda 4.11.0

python -V
Python 3.7.11
```

**Comment by geblanco** [comment] 2022-03-02 11:35
Hello,

I'm using python3.9 and having the same problem... Also happening on regular, consecutive calls...
I'll try using python3.7 and report back!

**Comment by geblanco** [comment] 2022-03-02 11:43
Just tried with python3.7 and still the same :(

**Comment by avarone-github** [comment] 2022-03-02 12:00
Hello @geblanco, thank you for your tests. Can you please try with v. 2.3.0 of **expertai-nlapi**?

**Comment by geblanco** [comment] 2022-03-02 12:05
Hello @avarone-github, yes it seems to solve the problem!
We have a bulk processing ahead, so it's the perfect time to check, I'll report if anything arises.

Thanks again!
Best,

**Comment by avarone-github** [comment] 2022-03-02 12:47
Thank you again @geblanco. I think I found the reason of the issue and also the reason why I couldn't reproduce it.
@fbottazzoli, please revert to version 2.3.0 of **expertai-nlapi** and let me know if it works for you too.

**Comment by fbottazzoli** [comment] 2022-03-02 18:45
Hi @avarone-github , with version 2.3.0 it works! Thank you a lot for you help and thank you also to @geblanco !

**Comment by avarone-github** [comment] 2022-03-03 07:51
Thank you @fbottazzoli and @geblanco for finding the bug and all the help.
Yesterday I pushed what I believe is the resolution of the problem.
After some further testing, I will close this issue and publish version 2.4.1 on PyPi and conda-forge. Until then please continue using v. 2.3.0 or, if you are a daring experimenter, clone the **master** branch and try using it, any feedback would be greatly appreciated.

**Comment by avarone-github** [comment] 2022-03-17 07:49
I'm closing the issue since it seems fixed in v. 2.4.1.

**Closed by avarone-github** 2022-03-17 07:49 UTC
